version: 2
updates:
  - package-ecosystem: cargo
    directory: /stellaux_server
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: cargo

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: client
